version: 2
jobs:
  build:
    docker:
      - image: circleci/node:15.1
    branches:
      only:
        - main
    steps:
      - checkout
      - run: echo "A first hello"
      - run: npm -v
      - run:
          name: Install
          command: npm install
      - run:
          name: Build
          command: npm run build