defaults: &defaults
docker: 
  -image: circleci/node:15.1
version: 2.1
jobs:
  prepare:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
        key:
          - v2-dependencies-{{ checksum "package.json" }}
      - run: yarn install
      - save_cache: 
        paths:
        - node-modules
        key: v2-dependencies-{{ checksum "package.json" }}
      - persist_to_workspace:
        root: .
        paths:
        - node-modules
  build: 
    <<: *defaults
    steps: 
    - checkout
    - attach_workspace:
      at: .
    run: yarn build
    - persist_to_workspace:
     root: .
      paths:
      - dist
  test:
    <<: *defaults
    steps: 
    - checkout
    - attach_workspace:
      at: .
    run: yarn test

workflows:
version: 2.1
build_accept_deploy:
  jobs: 
    - prepare
    - build:
      requires:
      - test
    - test:
      requires:
      -prepare
